# Generated by Django 5.0.6 on 2026-05-31 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_plate', models.CharField(max_length=10, verbose_name='Placa')),
                ('vehicle_label', models.CharField(max_length=200, verbose_name='Rótulo do veículo')),
                ('driver_name', models.CharField(max_length=150, verbose_name='Nome do solicitante')),
                ('driver_initials', models.CharField(max_length=4, verbose_name='Iniciais')),
                ('sector', models.CharField(max_length=100, verbose_name='Setor')),
                ('destination', models.CharField(max_length=255, verbose_name='Destino')),
                ('date', models.DateField(verbose_name='Data')),
                ('departure_time', models.TimeField(verbose_name='Hora de saída')),
                ('return_time', models.TimeField(verbose_name='Hora de retorno')),
                ('km', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='KM percorrido')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('reservado', 'Reservado'), ('em-uso', 'Em uso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('recusada', 'Recusada')], default='pendente', max_length=15, verbose_name='Status')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='Observação do admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='veiculos.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-created_at'],
            },
        ),
    ]
