# Generated by Django 5.0.6 on 2026-05-31 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('fuel', models.CharField(max_length=50, verbose_name='Combustível')),
                ('km', models.PositiveIntegerField(default=0, verbose_name='Quilometragem atual')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Capacidade (pessoas)')),
                ('type', models.CharField(max_length=50, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em-uso', 'Em uso'), ('manutencao', 'Em manutenção')], default='disponivel', max_length=15, verbose_name='Status')),
                ('current_driver', models.CharField(blank=True, max_length=150, null=True, verbose_name='Motorista atual')),
                ('current_driver_initials', models.CharField(blank=True, max_length=4, null=True, verbose_name='Iniciais motorista')),
                ('current_destination', models.CharField(blank=True, max_length=255, null=True, verbose_name='Destino atual')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Hora saída')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['brand', 'model'],
            },
        ),
    ]
