# Generated by Django 5.0.6 on 2026-06-12 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='type',
            new_name='vehicle_type',
        ),
    ]
